# Generated by Django 5.2.4 on 2025-08-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantor',
            name='nome',
        ),
    ]
